[build]
  command = "bundle exec jekyll build"
  publish = "_site"
  functions = "functions"

[dev]
  command = "bundle exec jekyll serve"
  port = 8888

[functions]
  directory = "functions"

# Enable Netlify Identity for CMS authentication
[identity]
  settings = {external_providers=["github"], roles=["admin", "editor"]}

# Git Gateway settings for Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
