backend:
  name: git-gateway
  branch: main
media_folder: 'assets/images'
public_folder: '/assets/images'
collections:
  - name: 'pages'
    label: 'Pages'
    folder: '_pages'
    create: true
    slug: '{{slug}}.md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}.md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
