name: Security Monitoring

on:
  schedule:
    # Run security scans every night at 2 AM
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm security audit
        run: |
          npm audit --audit-level=moderate --json > npm-audit.json
          cat npm-audit.json

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Semgrep security scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/javascript
            p/typescript

      - name: Check for vulnerable dependencies
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Create security issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Security Vulnerability Detected - ${new Date().toISOString().split('T')[0]}`;
            const body = `
            ## 🔒 Security Alert

            **PRIORITY:** HIGH
            **Detected:** ${new Date().toISOString()}

            The automated security scan has detected potential vulnerabilities in the Town of Wiley website.

            ### Required Actions:
            1. Review the security scan results in the workflow logs
            2. Update vulnerable dependencies immediately
            3. Check for exposed secrets or sensitive data
            4. Verify all security patches are applied

            ### Compliance Note:
            As a government website, maintaining security standards is critical for:
            - Protecting citizen data
            - Meeting federal security requirements
            - Maintaining public trust

            **This issue should be addressed within 24 hours.**
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'high-priority', 'government-compliance']
            });

  cve-monitoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Monitor for new CVEs
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'cve-report.json'

      - name: Upload CVE report
        uses: actions/upload-artifact@v4
        with:
          name: cve-report
          path: cve-report.json
